Repository boostcamp-2020/Project15-B-Client-Based-Formula-Editor, pull requests merged in 2020-12, with the labels that each got.

#17 GitHub Action을 이용한 자동배포 설정 파일 생성 및 누락된 테스트 작성
  .github/workflows/ncloud.yml
  test/presentationals/DropdownItems.test.jsx
Labels: config, test

#19 레이아웃의 약간의 변경 및 ListItem 삭제 버튼 추가
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/title.png
  src/containers/FontContainer.jsx
  src/icons/CloseIcon.jsx
  src/icons/ExclamationIcon.jsx
  src/layouts/FontContainerLayout.js
  src/layouts/ListLayout.js
  src/presentationals/EmptyItem.jsx
  src/presentationals/FontColorSelector.jsx
  src/presentationals/FontSizeSelector.jsx
  src/presentationals/ListItem.jsx
  src/presentationals/Title.jsx
  test/presentationals/EmptyItem.test.jsx
  test/presentationals/ListItem.test.jsx
  webpack.config.js
Labels: config, layout

#22 북마크 탭 기능 구현
  src/constants/sidebarTab.js
  src/containers/BookmarkContainer.jsx
  src/containers/SideBar.jsx
  src/presentationals/BookmarkAddButton.jsx
  src/presentationals/ListItem.jsx
  src/slice.js
  test/presentationals/BookmarkAddButton.test.jsx
  test/presentationals/ListItem.test.jsx
Labels: feature

#20 하단 버튼들에 대한 기능 구현 및 테스트 작성
  .github/workflows/ncloud.yml
  package-lock.json
  package.json
  src/App.jsx
  src/containers/FooterContainer.jsx
  src/containers/RouterExceptionCatcher.jsx
  src/presentationals/BubblePopup.jsx
  src/presentationals/FooterButton.jsx
  src/slice.js
  test/containers/FooterContainer.test.jsx
  test/presentationals/BubblePopup.test.jsx
Labels: feature, test

#21 커스텀 명령어 탭 기능 구현
  src/constants/sidebarTab.js
  src/containers/BookmarkContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/SideBar.jsx
  src/presentationals/BookmarkAddButton.jsx
  src/presentationals/CustomForm.jsx
  src/presentationals/CustomItem.jsx
  src/presentationals/CustomList.jsx
  src/presentationals/ListItem.jsx
  src/slice.js
  test/presentationals/BookmarkAddButton.test.jsx
  test/presentationals/CustomForm.test.jsx
  test/presentationals/CustomList.test.jsx
  test/presentationals/ListItem.test.jsx
Labels: feature

#23 최근 수식 기능 구현 및 북마크와 상태 공유 리팩토링
  src/constants/sidebarTab.js
  src/containers/BookmarkContainer.jsx
  src/containers/FooterContainer.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/presentationals/ListItem.jsx
  src/presentationals/SideBarTab.jsx
  src/slice.js
  src/util.js
  test/presentationals/SideBarTab.test.jsx
Labels: bug, feature, refactor

#24 디바운스를 이용한 임시저장 로직 구현
  src/containers/BodyContainer.jsx
  src/containers/FooterContainer.jsx
  src/presentationals/BubblePopup.jsx
  src/presentationals/FooterButton.jsx
  src/slice.js
  src/sliceUtil.js
  src/util.js
  test/containers/FooterContainer.test.jsx
  test/presentationals/CustomForm.test.jsx
Labels: feature, test

#25 MathQuill에서 지원하지 않는 latex command 주석 처리
  src/constants/characterLatex.js
Labels: bug

#26 최근/북마크 탭 리팩토링 및 테스트, 버그 수정
  jest.config.js
  package.json
  src/containers/BookmarkContainer.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/layouts/SideBarLayout.js
  src/presentationals/BookmarkAddButton.jsx
  src/presentationals/ListItem.jsx
  src/slice.js
  src/sliceUtil.js
  test/presentationals/BookmarkAddButton.test.jsx
Labels: bug, config, feature, refactor, test

#27 커스텀 명령어 수식 화면에서 쓰여지는 기능 추가
  src/containers/BodyContainer.jsx
  src/containers/CustomContainer.jsx
  src/presentationals/CustomList.jsx
  src/presentationals/FormulaRepresentation.jsx
  src/slice.js
  src/sliceUtil.js
  src/util.js
Labels: feature, refactor

#30 커스텀 명령어 등록 form의 name 필드에 자동 focus 기능 추가
  src/presentationals/CustomForm.jsx
Labels: feature

#31 actionCreator 함수 파일 분리 및 커스텀 명령어 실행 방법 변경
  src/actionCreator.js
  src/containers/BodyContainer.jsx
  src/containers/RecentContainer.jsx
  src/slice.js
Labels: refactor

#32 북마크 추가 버튼과 커스텀 명령어 폼에 CSS 적용 및 임시저장 버그 수정
  src/constants/mathquillLatex.js
  src/containers/BookmarkContainer.jsx
  src/containers/CustomContainer.jsx
  src/icons/DeleteIcon.jsx
  src/icons/EditIcon.jsx
  src/presentationals/BookmarkAddButton.jsx
  src/presentationals/CustomAddButton.jsx
  src/presentationals/CustomForm.jsx
  src/presentationals/CustomItem.jsx
  src/presentationals/CustomList.jsx
  src/slice.js
Labels: bug, feature

#33 사이드바 외부 영역 클릭할 때 사이드바가 닫히는 기능 보완
  src/App.jsx
  src/GlobalStyle.js
  src/containers/SideBar.jsx
  src/layouts/MainWrapper.js
Labels: bug

#35 라우터에서 params 로직을 queryString 로직으로 변경
  src/App.jsx
  src/containers/FooterContainer.jsx
  src/containers/RouterExceptionCatcher.jsx
  src/util.js
Labels: feature

#37 커스텀 명령어 탭 내 레이아웃 개선
  src/containers/CustomContainer.jsx
  src/containers/SideBar.jsx
  src/presentationals/CustomAddButton.jsx
  src/presentationals/CustomForm.jsx
  src/presentationals/CustomItem.jsx
  src/presentationals/CustomList.jsx
  test/presentationals/CustomList.test.jsx
Labels: bug, layout, refactor

#38 커스텀 명령어 에러 해결 및 사이드바 탭 전체삭제 버튼기능 구현
  src/actionCreator.js
  src/containers/BodyContainer.jsx
  src/containers/BookmarkContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/RecentContainer.jsx
  src/presentationals/SideBarHeader.jsx
  src/slice.js
  test/presentationals/CustomForm.test.jsx
Labels: bug, feature

#39 3주차 작업 내용 배포
  README.md
  src/actionCreator.js
  src/containers/BodyContainer.jsx
  src/containers/BookmarkContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/presentationals/CustomAddButton.jsx
  src/presentationals/CustomForm.jsx
  src/presentationals/CustomItem.jsx
  src/presentationals/CustomList.jsx
  src/presentationals/SideBarHeader.jsx
  src/slice.js
  test/presentationals/CustomForm.test.jsx
  test/presentationals/CustomList.test.jsx
Labels: deploy

#56 하단 버튼의 버블팝업 스타일 변경
  src/presentationals/BubblePopup.jsx
  src/presentationals/FooterButton.jsx
Labels: refactor

#57 URL로 query string이 들어오면 제거해주는 로직 구현
  src/App.jsx
  src/containers/QueryStringCatcher.jsx
Labels: feature

#58 confirm 팝업 생성 및 리팩토링
  src/actionCreator.js
  src/containers/BookmarkContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/presentationals/ConfirmModal.jsx
  src/presentationals/Title.jsx
  src/slice.js
  src/sliceUtil.js
Labels: feature, refactor

#59 VSCode theme의 기본적인 레이아웃 설정
  src/App.jsx
  src/GlobalStyle.js
  src/constants/sidebarTab.js
  src/containers/BodyContainer.jsx
  src/containers/BookmarkContainer.jsx
  src/containers/CharacterContainer.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/icons/PageIcon.jsx
  src/layouts/BodyLayout.js
  src/layouts/ControlContainerLayout.js
  src/layouts/EditTabHeaderLayout.js
  src/layouts/FontContainerLayout.js
  src/layouts/MainLayout.js
  src/layouts/MainWrapper.js
  src/layouts/SideBarLayout.js
  src/presentationals/FontColorSelector.jsx
  src/presentationals/FontSizeSelector.jsx
  src/presentationals/FormulaRepresentation.jsx
  src/presentationals/IconButton.jsx
  src/presentationals/LatexRepresentation.jsx
  src/presentationals/SideBarTab.jsx
Labels: feature

#61 사이드바 UI 테마 변경: VScode theme
  src/App.jsx
  src/GlobalStyle.js
  src/actionCreator.js
  src/constants/characterLatex.js
  src/containers/BookmarkContainer.jsx
  src/containers/CharacterContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/icons/DownIcon.jsx
  src/icons/PlusIcon.jsx
  src/icons/RightIcon.jsx
  src/layouts/BodyLayout.js
  src/layouts/CharacterContainerLayout.js
  src/layouts/MainLayout.js
  src/layouts/MainWrapper.js
  src/layouts/SideBarLayout.js
  src/layouts/SideTabItemLayout.js
  src/presentationals/BlueButton.jsx
  src/presentationals/BookmarkAddButton.jsx
  src/presentationals/CharacterList.jsx
  src/presentationals/CharacterListItem.jsx
  src/presentationals/CustomAddButton.jsx
  src/presentationals/CustomForm.jsx
  src/presentationals/CustomItem.jsx
  src/presentationals/DirectoryTitle.jsx
  src/presentationals/Filter.jsx
  src/presentationals/ListItem.jsx
  src/presentationals/PromptModal.jsx
  src/presentationals/SideBarTab.jsx
  src/slice.js
  src/sliceUtil.js
  src/util.js
Labels: feature, layout, refactor, upgrade

#60 메인화면 UI 변경 및 메인 컨텐츠 크기 설정 관련 기능 추가
  src/App.jsx
  src/GlobalStyle.js
  src/containers/BodyContainer.jsx
  src/containers/FooterContainer.jsx
  src/icons/AngleDownIcon.jsx
  src/icons/AngleUpIcon.jsx
  src/layouts/BodyLayout.js
  src/layouts/CharacterContainerLayout.js
  src/layouts/DropdownWrapper.js
  src/layouts/FooterButtonWrapper.js
  src/layouts/FooterLayout.js
  src/layouts/MainContentWrapper.js
  src/layouts/MainLayout.js
  src/presentationals/BubblePopup.jsx
  src/presentationals/DynamicBar.jsx
  src/presentationals/FontSizeSelector.jsx
  src/presentationals/FooterButton.jsx
  src/presentationals/FormulaRepresentation.jsx
  src/presentationals/LatexRepresentation.jsx
  src/presentationals/ListItem.jsx
  src/slice.js
Labels: feature, layout, upgrade

#62 사이드바와 편집기 사이의 resize 기능 구현
  src/App.jsx
  src/GlobalStyle.js
  src/constants/size.js
  src/containers/MainContainer.jsx
  src/containers/SideBar.jsx
  src/layouts/BodyLayout.js
  src/layouts/MainContentWrapper.js
  src/layouts/SideBarContentLayout.js
  src/layouts/SideBarLayout.js
  src/presentationals/CharacterListItem.jsx
  src/presentationals/DynamicBarHorizontal.jsx
  src/presentationals/FormulaRepresentation.jsx
  src/util.js
Labels: feature, layout, refactor

#63 Dynamic Bar 크기 조절 할 때 수직 이동만 하도록 수정
  src/GlobalStyle.js
  src/containers/BodyContainer.jsx
  src/layouts/BodyLayout.js
  src/layouts/DropdownWrapper.js
  src/presentationals/CustomForm.jsx
  src/presentationals/DynamicBar.jsx
  src/presentationals/DynamicBarHorizontal.jsx
  src/presentationals/GhostBar.jsx
Labels: layout, refactor

#64 자동완성 기능 구현
  src/actionCreator.js
  src/constants/keyCode.js
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/containers/CharacterContainer.jsx
  src/icons/NotificationIcon.jsx
  src/presentationals/AutoComplete.jsx
  src/presentationals/BubblePopup.jsx
  src/presentationals/FontSizeSelector.jsx
  src/slice.js
Labels: feature

#65 글로벌 팝업 구현 및 적용
  README.md
  src/GlobalStyle.js
  src/actionCreator.js
  src/constants/keyCode.js
  src/constants/mathquillLatex.js
  src/containers/AutoKeywordContainer.jsx
  src/containers/BookmarkContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/layouts/SideTabItemLayout.js
  src/popup.js
  src/popupStyle.js
  src/slice.js
  src/util.js
Labels: feature

#66 VSCode Theme 레이아웃 거의 다 적용 및 Footer버튼 사이드바 하단 탭으로 이동
  README.md
  public/favicon.ico
  public/index.html
  src/GlobalStyle.js
  src/constants/size.js
  src/containers/BodyContainer.jsx
  src/containers/FooterContainer.jsx
  src/containers/MainContainer.jsx
  src/containers/SideBar.jsx
  src/icons/ImageFileIcon.jsx
  src/icons/SaveIcon.jsx
  src/icons/ShareIcon.jsx
  src/layouts/BodyLayout.js
  src/layouts/EditTabHeaderLayout.js
  src/layouts/FooterLayout.js
  src/layouts/MainContentWrapper.js
  src/layouts/MainLayout.js
  src/layouts/SideBarTabLayout.js
  src/popup.js
  src/popupStyle.js
  src/presentationals/DynamicBarHorizontal.jsx
  src/presentationals/DynamicBarVertical.jsx
  src/presentationals/FontSizeSelector.jsx
  src/presentationals/FooterButton.jsx
  src/presentationals/FormulaRepresentation.jsx
  src/presentationals/GhostBar.jsx
  src/presentationals/IconButton.jsx
  src/presentationals/LatexRepresentation.jsx
  src/presentationals/SideBottomTab.jsx
  src/presentationals/SideTopTab.jsx
  test/containers/FooterContainer.test.jsx
  test/presentationals/FooterButton.test.jsx
  test/presentationals/SideBarTab.test.jsx
Labels: layout, refactor, upgrade

#67 사이드바 검색 기능 추가
  src/containers/BookmarkContainer.jsx
  src/containers/CharacterContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/RecentContainer.jsx
  src/presentationals/DirectoryTitle.jsx
  src/presentationals/Filter.jsx
Labels: feature

#68 커스텀 폼 설명 입력 란 추가
  src/containers/CustomContainer.jsx
  src/presentationals/CustomForm.jsx
  src/slice.js
Labels: feature, layout

#70 최근 수식 탭에서 즐찾 추가 버그 & 리스트 비었을 때 보여주는 문구 색상 변경
  README.md
  src/containers/RecentContainer.jsx
  src/presentationals/EmptyItem.jsx
Labels: bug, layout

#88 버그 몇 가지 픽스 및 README 수정
  README.md
  src/GlobalStyle.js
  src/layouts/MainLayout.js
  src/presentationals/CustomForm.jsx
Labels: bug, documentation

#90 GitHub Action으로 Test 설정
  .github/workflows/action.yml
  .github/workflows/ncloud.yml
  babel.config.js
  package-lock.json
  package.json
  src/actionCreator.js
  src/containers/FormulaButtonContainer.jsx
  src/containers/HeaderContainer.jsx
  src/icons/AlphaIcon.jsx
  src/icons/FxIcon.jsx
  src/icons/GreaterThanIcon.jsx
  src/icons/LessThanIcon.jsx
  src/icons/RootIcon.jsx
  src/layouts/ButtonMenuLayout.js
  src/layouts/FooterButtonWrapper.js
  src/layouts/ListLayout.js
  src/popup.js
  src/presentationals/ConfirmModal.jsx
  src/presentationals/DropdownItem.jsx
  src/presentationals/DropdownItems.jsx
  src/presentationals/EditTabButton.jsx
  src/presentationals/FormulaButton.jsx
  src/presentationals/PromptModal.jsx
  src/presentationals/SideBarHeader.jsx
  src/presentationals/Title.jsx
  test/presentationals/BookmarkAddButton.test.jsx
  test/presentationals/CustomAddButton.test.jsx
  test/presentationals/CustomItem.test.jsx
  test/presentationals/DropdownItem.test.jsx
  test/presentationals/DropdownItems.test.jsx
  test/presentationals/EditTabButton.test.jsx
  test/presentationals/FontSizeSelector.test.jsx
  test/presentationals/FormulaButton.test.jsx
  test/presentationals/SideBarHeader.test.jsx
  test/presentationals/Title.test.jsx
Labels: feature, test

#94 사이드바 열고 닫는 기능 구현
  src/actionCreator.js
  src/constants/sidebarTab.js
  src/containers/BodyContainer.jsx
  src/containers/MainContainer.jsx
  src/containers/SideBar.jsx
  src/layouts/BodyLayout.js
  src/layouts/SideBarLayout.js
  src/presentationals/SideTopTab.jsx
  src/slice.js
Labels: feature, layout

#93 Presentational 컴포넌트들에 대한 테스트 작성
  test/presentationals/AutoComplete.test.jsx
  test/presentationals/BlueButton.test.jsx
  test/presentationals/CharacterList.test.jsx
  test/presentationals/CharacterListItem.test.jsx
  test/presentationals/CustomForm.test.jsx
  test/presentationals/DirectoryTitle.test.jsx
  test/presentationals/DynamicBarHorizontal.test.jsx
  test/presentationals/DynamicBarVertical.test.jsx
Labels: test

#95 이미지 저장과 관련한 버그 수정 및 기능 추가
  src/GlobalStyle.js
  src/containers/SideBar.jsx
  src/popup.js
  src/popupStyle.js
Labels: bug, feature

#96 루트모양 깨지던 버그 및 여러 버그 수정
  src/actionCreator.js
  src/layouts/SideBarContentLayout.js
  src/layouts/SideTabItemLayout.js
  src/presentationals/CharacterListItem.jsx
  src/presentationals/CustomItem.jsx
  src/presentationals/ListItem.jsx
Labels: bug, layout

#98 아이콘 hover 시 타이틀 표시 & 자동 완성 버그 수정
  src/containers/AutoKeywordContainer.jsx
  src/icons/CustomIcon.jsx
  src/icons/EmptyStarIcon.jsx
  src/icons/ImageFileIcon.jsx
  src/icons/PageIcon.jsx
  src/icons/PlusIcon.jsx
  src/icons/RedoIcon.jsx
  src/icons/ResetIcon.jsx
  src/icons/SaveIcon.jsx
  src/icons/ShareIcon.jsx
  src/icons/TimeIcon.jsx
  src/icons/UndoIcon.jsx
  src/presentationals/AutoComplete.jsx
Labels: bug, layout

#103 자동완성과 horizontal bar hover 버그 수정 및 글로벌 팝업 업그레이드
  src/containers/AutoKeywordContainer.jsx
  src/popup.js
  src/presentationals/DynamicBarVertical.jsx
  src/presentationals/LatexRepresentation.jsx
Labels: bug, refactor, upgrade

#104 undo/redo 버그 수정
  src/actionCreator.js
  src/containers/AutoKeywordContainer.jsx
  src/slice.js
  src/sliceUtil.js
Labels: bug

#105 팝업 및 커스텀 폼에서 공백 예외처리
  src/containers/CustomContainer.jsx
  src/popup.js
  src/popupStyle.js
  src/presentationals/CustomForm.jsx
  src/slice.js
  test/presentationals/CustomForm.test.jsx
Labels: bug

#106 폰트 크기 설정을 select-option에서 커스텀으로 변경
  src/constants/fontConfig.js
  src/containers/FontContainer.jsx
  src/icons/CheckIcon.jsx
  src/presentationals/FontSizeSelector.jsx
  test/presentationals/FontSizeSelector.test.jsx
Labels: upgrade

#109 자동 완성 클릭으로 선택하는 기능 구현
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/presentationals/AutoComplete.jsx
  src/util.js
Labels: feature, upgrade

#111 사이드 탭에 Example 템플릿 구현
  src/constants/characterLatex.js
  src/containers/CharacterContainer.jsx
  src/presentationals/CharacterList.jsx
  src/presentationals/CharacterListItem.jsx
  src/slice.js
Labels: feature

#112 자동완성 중 커서 이동 후 자동완성 기능이 제대로 동작하지 않는 버그 수정
  babel.config.js
  package-lock.json
  package.json
  src/constants/keyCode.js
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/util.js
  webpack.config.js
Labels: bug, config

#113 FontSize Dropdown UI 수정 및 ListItem 접근성 및 버그 해결
  src/GlobalStyle.js
  src/containers/BookmarkContainer.jsx
  src/containers/CharacterContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/FontContainer.jsx
  src/containers/RecentContainer.jsx
  src/hooks.js
  src/icons/DeleteIcon.jsx
  src/icons/EditIcon.jsx
  src/icons/MinusIcon.jsx
  src/layouts/CharacterContainerLayout.js
  src/layouts/SideBarLayout.js
  src/presentationals/CharacterList.jsx
  src/presentationals/CharacterListItem.jsx
  src/presentationals/CustomItem.jsx
  src/presentationals/EmptyItem.jsx
  src/presentationals/FontSizeSelector.jsx
  src/presentationals/ListItem.jsx
  src/slice.js
  src/util.js
  test/presentationals/CharacterList.test.jsx
  test/presentationals/CustomItem.test.jsx
  test/presentationals/ListItem.test.jsx
Labels: bug, layout

#114 북마크 이름 변경 기능 구현
  src/containers/BookmarkContainer.jsx
  src/popup.js
  src/presentationals/FontColorSelector.jsx
  src/presentationals/ListItem.jsx
  src/sliceUtil.js
Labels: feature

#117 자동완성 기능을 사용할 때 발생하는 버그 수정
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/util.js
Labels: bug

#119 프레젠테이셔널 레이어 테스트 완료
  test/presentationals/EmptyItem.test.jsx
  test/presentationals/Filter.test.jsx
  test/presentationals/FormulaRepresentation.test.jsx
  test/presentationals/GhostBar.test.jsx
  test/presentationals/IconButton.test.jsx
  test/presentationals/LatexRepresentation.test.jsx
  test/presentationals/SideBottomTab.test.jsx
  test/presentationals/SideTopTab.test.jsx
Labels: test

#120 font 크기 관련 기능 보완
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/containers/FontContainer.jsx
  src/presentationals/AutoComplete.jsx
  src/presentationals/FontSizeSelector.jsx
  test/presentationals/FontSizeSelector.test.jsx
Labels: refactor, upgrade

#121 아이콘 타이틀 추가 및 안쓰이는 아이콘 삭제
  src/icons/AlignCenterIcon.jsx
  src/icons/AlignLeftIcon.jsx
  src/icons/AlignRightIcon.jsx
  src/icons/EditIcon.jsx
  src/icons/EmptyCustomIcon.jsx
  src/icons/FilledCustomIcon.jsx
  src/icons/FilledStarIcon.jsx
  src/icons/FontIcon.jsx
  src/icons/FontSizeIcon.jsx
  src/icons/MinusIcon.jsx
  src/icons/PlusIcon.jsx
Labels: layout

#118 튜토리얼 기능 구현
  package-lock.json
  public/FormulaRepresentation.gif
  public/FormulaRepresentation_top.gif
  public/LatexRepresantation.gif
  public/SideBar_character.gif
  public/SideTab_bottom.gif
  public/SideTab_top.gif
  public/dark_logo.png
  src/App.jsx
  src/constants/filePath.js
  src/containers/BodyContainer.jsx
  src/containers/SideBar.jsx
  src/containers/TutorialContainer.jsx
  src/icons/HelpIcon.jsx
  src/icons/UpIcon.jsx
  src/presentationals/SideBottomTab.jsx
  src/presentationals/TutorialMain.jsx
  src/presentationals/TutorialPage.jsx
  src/presentationals/TutorialStart.jsx
  src/slice.js
  test/presentationals/SideBottomTab.test.jsx
  test/presentationals/TutorialMain.test.jsx
  test/presentationals/TutorialPage.test.jsx
  test/presentationals/TutorialStart.test.jsx
Labels: feature

#122 커스텀 명령어 선택/클릭 자동 완성 기능 구현
  src/constants/mathquillLatex.js
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/presentationals/AutoComplete.jsx
  src/util.js
Labels: feature, upgrade

#124 컴포넌트 렌더링 최적화
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/containers/CharacterContainer.jsx
  src/containers/ControlButtonContainer.jsx
  src/containers/FontContainer.jsx
  src/containers/SideBar.jsx
  src/hooks.js
  src/presentationals/AutoComplete.jsx
  src/presentationals/BubblePopup.jsx
  src/presentationals/CharacterList.jsx
  src/presentationals/CharacterListItem.jsx
  src/presentationals/DirectoryTitle.jsx
  src/presentationals/FontSizeSelector.jsx
  src/presentationals/IconButton.jsx
  src/presentationals/SideBottomTab.jsx
  src/presentationals/SideTopTab.jsx
Labels: refactor

#123 자동완성 리스트에 페이지 기능 추가
  src/containers/AutoKeywordContainer.jsx
Labels: bug, feature

#127 튜토리얼 기능을 반응형으로 다시 구현
  public/SideTab_top.gif
  src/containers/TutorialContainer.jsx
  src/icons/FlagIcon.jsx
  src/icons/NextIcon.jsx
  src/icons/PrevIcon.jsx
  src/icons/UpIcon.jsx
  src/presentationals/TutorialMain.jsx
  src/presentationals/TutorialPage.jsx
  src/presentationals/TutorialStart.jsx
  test/presentationals/TutorialMain.test.jsx
  test/presentationals/TutorialPage.test.jsx
Labels: bug, upgrade

#128 컨테이너 테스트 코드 추가
  test/containers/RecentContainer.test.jsx
  test/containers/SideBar.test.jsx
  test/presentationals/FormulaRepresentation.test.jsx
  test/presentationals/IconButton.test.jsx
Labels: test

#129 ListItem이 진입하는 각도에 따라 달라 접근성 어려운 문제 해결
  src/hooks.js
Labels: upgrade

#130 copy-plugin-webpack 패키지 추가 및 MainLayout 최소 높이 변경
  package-lock.json
  package.json
  src/layouts/MainLayout.js
  src/slice.js
  src/store.js
  webpack.config.js
Labels: config, upgrade

#131 갖가지 오류 수정 해결
  src/App.jsx
  src/actionCreator.js
  src/containers/AutoKeywordContainer.jsx
  src/containers/SideBar.jsx
  src/containers/TutorialContainer.jsx
  src/popup.js
  src/popupStyle.js
  src/slice.js
Labels: bug

#140 테마 변경 기능(Dark/Light) 추가
  src/App.jsx
  src/GlobalStyle.js
  src/actionCreator.js
  src/constants/color.js
  src/constants/size.js
  src/constants/theme.js
  src/containers/AutoKeywordContainer.jsx
  src/containers/BodyContainer.jsx
  src/containers/BookmarkContainer.jsx
  src/containers/CharacterContainer.jsx
  src/containers/ControlButtonContainer.jsx
  src/containers/CustomContainer.jsx
  src/containers/FontContainer.jsx
  src/containers/MainContainer.jsx
  src/containers/QueryStringCatcher.jsx
  src/containers/RecentContainer.jsx
  src/containers/SideBar.jsx
  src/containers/ThemeContainer.jsx
  src/containers/TutorialContainer.jsx
  src/icons/EditIcon.jsx
  src/icons/FilledStarIcon.jsx
  src/icons/HelpIcon.jsx
  src/icons/MinusIcon.jsx
  src/icons/MoonIcon.jsx
  src/icons/PageIcon.jsx
  src/icons/PlusIcon.jsx
  src/icons/SunIcon.jsx
  src/layouts/BodyLayout.js
  src/layouts/CharacterContainerLayout.js
  src/layouts/ControlContainerLayout.js
  src/layouts/EditTabHeaderLayout.js
  src/layouts/FontContainerLayout.js
  src/layouts/SideBarContentLayout.js
  src/layouts/SideBarTabLayout.js
  src/popupStyle.js
  src/presentationals/AutoComplete.jsx
  src/presentationals/BlueButton.jsx
  src/presentationals/BubblePopup.jsx
  src/presentationals/CharacterList.jsx
  src/presentationals/CharacterListItem.jsx
  src/presentationals/CustomForm.jsx
  src/presentationals/DirectoryTitle.jsx
  src/presentationals/DynamicBarHorizontal.jsx
  src/presentationals/DynamicBarVertical.jsx
  src/presentationals/EmptyItem.jsx
  src/presentationals/Filter.jsx
  src/presentationals/FontColorSelector.jsx
  src/presentationals/FontSizeSelector.jsx
  src/presentationals/FormulaRepresentation.jsx
  src/presentationals/GhostBar.jsx
  src/presentationals/LatexRepresentation.jsx
  src/presentationals/ListItem.jsx
  src/presentationals/SideBottomTab.jsx
  src/presentationals/SideTopTab.jsx
  src/presentationals/ThemeButton.jsx
  src/presentationals/TutorialMain.jsx
  src/presentationals/TutorialPage.jsx
  src/presentationals/TutorialStart.jsx
  src/slice.js
  src/util.js
Labels: bug, feature, layout, refactor, upgrade

#142 튜토리얼 항상 Skip 버튼 떠있게 변경 및 테스트 코드 작성
  src/containers/TutorialContainer.jsx
  src/presentationals/SkipButton.jsx
  src/presentationals/TutorialMain.jsx
  src/presentationals/TutorialStart.jsx
  test/presentationals/SkipButton.test.jsx
  test/presentationals/ThemeButton.test.jsx
  test/presentationals/TutorialStart.test.jsx
Labels: refactor, test

#144 최근 수식과 북마크의 아이템이 수식 입력 영역에 추가되도록 변경
  src/containers/BookmarkContainer.jsx
  src/containers/RecentContainer.jsx
Labels: upgrade

#147 자동완성할 때 제대로 동작하지 않는 LaTeX 명령어 삭제
  src/constants/mathquillLatex.js
Labels: hotfix

#146 팝업보다 테마변경버튼이 위로 올라오는 버그 및 몇가지 버그 수정
  src/containers/BookmarkContainer.jsx
  src/popupStyle.js
  src/presentationals/AutoComplete.jsx
Labels: hotfix

#148 라이트 모드에서 커스텀 폼 글씨 색상 변경
  src/presentationals/CustomForm.jsx
Labels: hotfix

#149 Hotfix 내용 master 브랜치에 반영
  src/constants/mathquillLatex.js
  src/containers/BookmarkContainer.jsx
  src/popupStyle.js
  src/presentationals/AutoComplete.jsx
  src/presentationals/CustomForm.jsx
Labels: deploy, hotfix
